# Generated by Django 5.1 on 2024-08-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magentoData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product_id_id',
        ),
    ]
