# Generated by Django 5.1 on 2024-08-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentoData', '0002_inventory_alter_product_bundle_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code_id', models.CharField(max_length=255)),
                ('store_view_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoreCodeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_code_products', to='magentoData.product')),
                ('store_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_code_products', to='magentoData.storecode')),
            ],
        ),
    ]
