# Generated by Django 5.1 on 2024-08-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentoData', '0002_alter_customers_customer_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
