# Generated by Django 5.1 on 2024-08-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magentoData', '0003_remove_orders_customer_orders_customer_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
