# Generated by Django 5.1 on 2024-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentoData', '0004_alter_inventory_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
