# Generated by Django 5.1 on 2024-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentoData', '0004_rename_customer_name_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
