# Generated by Django 5.1 on 2024-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentoData', '0005_alter_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
    ]
